#### **Q1:** Define z with value 10 and cast it as an int following the above rubric for class/ data type definition:

In [6]:
z = int(10)

#### **Q2:** Enter the name of this course as a string and assign it to the variable "course_name". Then verify its type is a string:

In [5]:
course_name = str("ME 003")
type(course_name)

str

#### **Q3:** Type *import math* to import the math library. On the next line enter the dir command to see the methods in the math library. Then get help on the square root method. 

In [7]:
import math
dir(math)
help(math.sqrt)

Help on built-in function sqrt in module math:

sqrt(...)
    sqrt(x)
    
    Return the square root of x.



#### **Q4:** Define a variable "tasty" with class float and value 3.14 . On the next line print the text "The value of tasty is: " followed by variable tasty's value using the { } syntax (not just entering 3.14).

In [12]:
tasty = float(3.14)
print(f"The value of tasty is: {tasty}")

The value of tasty is: 3.14


#### **Q4.2:** Calculate the square root of 15129 using the math module and return the answer in a print statement "The square root of 15129 is:" 

In [13]:
import math
ans = int(math.sqrt(15129))
print(f"The square root of 15129 is: {ans}")

The square root of 15129 is: 123


#### **Q5:** Calculate the area of a circle with radius r = 3 and suppress the output at 3 decimal places:

In [14]:
import math 
r = 3
area = math.pi*r**2
print(f"The area of a circle with radius 3 is: {area:.3f}")

The area of a circle with radius 3 is: 28.274


#### **Q6**: Create a list called calendar with the 24 elements being the name of each month of the year followed directly by the number of that specific month. Then print "The months of the year are: (calendar list variable)"

In [15]:
calendar = ["January",1,"February",2,"March",3,"April",4,"May",5,"June",6,"July",7,"August",8,"September",9,"October",10,"Novemeber",11,"December",12]
print(f"The months of the year are: {calendar}")

The months of the year are: ['January', 1, 'February', 2, 'March', 3, 'April', 4, 'May', 5, 'June', 6, 'July', 7, 'August', 8, 'September', 9, 'October', 10, 'Novemeber', 11, 'December', 12]


#### **Q7:** Now make a list called "me" with elements of your name, birth year (yyyy) and college graduation year. Print the "me" list.<br>Then make a list called "UVM" with elements of the name of this university, the date of UVM's establishment (yyyy) and number of students in your class at UVM. Print the "UVM" list.<br> Then print the two lists concatenated. <br>Then print each list separately to confirm they were unchanged.

In [11]:
me = ["student's_name", 2000, 2023]
print(me)
UVM = ["The University of Vermont", 1791, 2500]
print(UVM)
print(me+UVM)
print(me)
print(UVM)

["student's_name", 2000, 2023]
['The University of Vermont', 1791, 2500]
["student's_name", 2000, 2023, 'The University of Vermont', 1791, 2500]
["student's_name", 2000, 2023]
['The University of Vermont', 1791, 2500]


#### **Q8:** Create a NumPy array called np_A_1 using the range function with even numbers from 2 to 10 (inclusive). Then divide it by 2 and print the result:

In [10]:
import numpy as np
np_A_1 = np.array(range(2,12,2))
print(np_A_1)
print(np_A_1/2)

[ 2  4  6  8 10]
[1. 2. 3. 4. 5.]


#### **Q9**: Print the 3rd index of L1. <br> Append to L1 the rest of the integers to 8 (inclusive) and then print the new version of L1:

In [16]:
L1 = [1,2,3,4]
#your code here:
print(L1[3])
L1.append(5)
L1.append(6)
L1.append(7)
L1.append(8)
print(L1)

4
[1, 2, 3, 4, 5, 6, 7, 8]


#### **Q10:** Using the range function, Create an array named A_2 with values of 1 to 20. <br> Then slice the values from 3 to 13 (inclusive) into a new array called A_2_s and print the new array:

In [17]:
import numpy as np
A_2 = np.array(range(1,21))
print(A_2)
A_2_s = A_2[3:13]
print(A_2_s)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 4  5  6  7  8  9 10 11 12 13]


#### **Q11:** Now make your own dictionary of the North Beach Park address called "NBP_a" using the dict() constructor with the same data structure as shown above *but omit the coordinates*. <br> Then add the coordinates using the above method. <br> Finally access the city value using its key.

In [19]:
# building = "North Beach Club House"
# number   = 1
# street   = "Institute Rd"
# city     = "Burlington"
# state    = "VT"
# zip      = 05401
# coord    = (44.492228, -73.240930)
NBP_a = dict(building = "North Beach Club House", number = 1,# "n/a is also ok here"
            street = "Institute Rd", city = "Burlington", 
            state = "VT", zip = "05401",)


#### **Q11.2:** Then add the coordinates using the square bracket method as described above.

In [20]:
NBP_a["coord"] = (44.492228, -73.240930)

#### **Q11.3:** Finally verify the coordinates were correctly added by accessing the coord value using its key.

In [22]:
NBP_a["coord"]

(44.492228, -73.24093)

#### **Q12:** Write an if statement that takes user input for their GPA and determines if they made the Dean's list and congratulates the student if applicable. (UVM's Dean's list: not less than 3.00 GPA who stood in the top 20 percent of each class of their college/school during the preceding semester.")

In [29]:
gpa = float(input("Enter your GPA: "))
if gpa >= 3.0:
    print("Congratulations! You qualified for the Dean's list!")

Congratulations! You qualified for the Dean's list!


#### **Q13:** Add to Q12, an else statement with a GPA difference calculator that prints to 2 decimal places and an incouraging statement if the student did not qualify for the Dean's List:

In [28]:
gpa = float(input("Enter your GPA: "))
if gpa >= 3.0:
    print("Congratulations! You qualified for the Dean's list!")
else:
    gpa_diff = 3.0 - gpa
    print(f"You were {gpa_diff:.2f} from making the Dean's List. Keep cranking & work smarter, not harder!")
        

Congratulations! You qualified for the Dean's list!


#### **Q14:** Create an exam letter grade calculator based upon the usual delineation: A >= 90, B >= 80, C >= 70, D >= 60, F < 60. It must take user input for the student's grade and print the corresponding letter grade. It must also produce an error message for entries greater than 100 and less than 0, say "Error! Enter a number between 0 and 100."

In [ ]:
grade = int(input("Enter your exam grade: "))
if grade <= 100 and grade >= 90:
    print("You earned an A!")
elif grade < 90 and grade >= 80:
    print("You earned a B!")
elif grade <80 and grade >= 70:
    print("You earned a C.")
elif grade <70 and grade >= 60:
    print("You earned a D.")
elif grade < 60:
    print("You failed.")
else:
    print("Error! Enter a number between 0 and 100.")

#### **Q15:** Develop a for loop that fills a zeros-initialized array with the first 10 perfect squares and prints the array at each iteration:

In [34]:
import numpy as np
A_square = np.array(np.zeros(10))
for i in range(11):
    square = i**2
    A_square[i-1] = square
    print(A_square)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 4. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 4. 9. 0. 0. 0. 0. 0. 0. 0.]
[ 1.  4.  9. 16.  0.  0.  0.  0.  0.  0.]
[ 1.  4.  9. 16. 25.  0.  0.  0.  0.  0.]
[ 1.  4.  9. 16. 25. 36.  0.  0.  0.  0.]
[ 1.  4.  9. 16. 25. 36. 49.  0.  0.  0.]
[ 1.  4.  9. 16. 25. 36. 49. 64.  0.  0.]
[ 1.  4.  9. 16. 25. 36. 49. 64. 81.  0.]
[  1.   4.   9.  16.  25.  36.  49.  64.  81. 100.]


#### **Q16:** Develop code that solves the previous problem using a while loop. (Hint: if in Q15 you struggled to produce the 10th perfect square (100), think about your index number when filling the array.)

In [35]:
import numpy as np
A_square = np.array(np.zeros(10))
i = 0
while i < 11:
    square = i**2
    A_square[i-1] = square 
    print(A_square)
    i += 1

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 4. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 4. 9. 0. 0. 0. 0. 0. 0. 0.]
[ 1.  4.  9. 16.  0.  0.  0.  0.  0.  0.]
[ 1.  4.  9. 16. 25.  0.  0.  0.  0.  0.]
[ 1.  4.  9. 16. 25. 36.  0.  0.  0.  0.]
[ 1.  4.  9. 16. 25. 36. 49.  0.  0.  0.]
[ 1.  4.  9. 16. 25. 36. 49. 64.  0.  0.]
[ 1.  4.  9. 16. 25. 36. 49. 64. 81.  0.]
[  1.   4.   9.  16.  25.  36.  49.  64.  81. 100.]


#### **Q17:** Define your own function that takes input of radius r, and height h, and calculates the area of a right circular cone to two decimal places (only accept positive input). The formula for the area of a right circular cone is: A = Pi•r•(r+sqrt(h^2 + r^2)). Hint you will need to import a module and follow PEMDAS carefully. Good luck!

In [36]:
import math
def r_cone(r,h):
    r = float(input("Enter a radius: "))
    while r <= 0:
        r = float(input("Enter a radius greater than 0: "))
    h = float(input("Enter a height: "))
    while h <= 0:
        h = float(input("Enter a height greater than 0: "))
    A = math.pi*r*(r + math.sqrt(h**2 + r**2))
    print(f"The area of a right circular cone with radius {r} and height {h} is: {A:.2f} ")
    

#### **Q18:** Correctly call the function you wrote in question 17 and show that it handles erroneous entries and correctly calculates entries  within the appropriate bounds.

In [37]:
r_cone(1,2)

The area of a right circular cone with radius 3.0 and height 3.0 is: 68.26 


#### **Q19:** Now create a function that takes user input for file_name and then opens that file in read mode and prints the contents of the file. The present working directory is assumed to be Course-Documents. 

In [4]:
def open_file(file_name):
    """open_file: Takes input argument of file_name (including file type) 
    and opens desired file."""
    f = open(file_name,"r")
    for line in f:
        print(line.strip())
        
open_file("Useful_websites.txt")

https://docs.python.org Python's official documentation page: anything Python 1st party related.<br>

https://docs.scipy.org Scientific Python (SciPy) official documentation page. SciPy are the creaters of Numpy, MatPlotLib and many other powerfull Python extensions. <br>

https://w3schools.com One of the cleanest general 3rd party tutorial sites on Python. <br>

https://stackoverflow.com Invaluable forum website for nearly any coding language. User posts question, another user (shows experience level) posts solution which gets voted up or down by other users based on accuracy. Type your question or Traceback error into Google and chances are someone has had the same problem or similar enough that you can extrapolate your answer. <br>

https://www.youtube.com/watch?v=bY6m6_IIN94&list=PLi01XoE8jYohWFPpC17Z-wWhPOSuh8Er- Socratica has a more interactive approach to teaching and learning with each video pased in console. (Console is a running display of both your input and immediately prin